### ISSUE TITLE
Record Rule Problems on Staging 2

### ISSUE THREAD

**Issue by nh758** [digi-serve/ab_platform_web#154]
From digi-serve/ns_app#91

- [ ] 13.2 Unable to add a new report item
- [ ] 13.3 Unable to submit an expense report

**Comment by Achoobert** [comment]
I had to fix something in the definitions to allow submitting an `Expense Report` in the test: it may be worthwhile to update the definitions on staging2?

**Comment by wongpratan** [comment]
13.2 Unable to add a new report item
When `Report Items` is added, its `Expense Report` value are not set.
I think we might need to set how to set `Expense Report` value.
For now, we don't have setup Record Rule or Parent DC to set.
![Screenshot from 2022-09-22 16-35-56](https://user-images.githubusercontent.com/545045/191729425-a79314b3-6d19-4027-8a40-48a43006428b.png)
![aa](https://user-images.githubusercontent.com/545045/191729457-af7822ac-9144-491b-86d8-0f7387159212.png)

13.3 Unable to submit an expense report

There is `Total` not equal `0` condition.
I tested some Report Items with `Total` are not `0` in my local. It works fine to me.
![Screenshot from 2022-09-22 17-17-02](https://user-images.githubusercontent.com/545045/191728870-cfeb534a-71eb-4ea6-8c43-25a2dce95489.png)

**Comment by jamesduncan** [comment]
@Achoobert what changes were made? I was wondering if there could be differences on staging2 than my local. Are we supporting definition changes on staging2? As in if we make a change are we expecting it to become the new "master" or are they just temporary changes that we know we need to make elsewhere before they are the new def?

**Comment by wongpratan** [comment]
It cause of `Expense Report - Current User` dc is using `My Person` query to filter but `My Team Finances` does not include that query.
![myperson](https://user-images.githubusercontent.com/545045/192287387-6655a90d-0399-4706-89b8-b4a770a8e2bd.png)

After I included that query into the application, then I can add new `Report Item` data with have properly `Expense Report` connected value. 

But there still is a issue to real time update feature.

**Comment by jamesduncan** [comment]
The definition issue may explain some of why it still works for me locally...but I don't understand why the real time update is working for me locally and not on staging2.

**Comment by jamesduncan** [comment]
I think this is fixed now. I just changed the definition of the "Expense Report - Current User" to match what I have locally.

**Comment by jamesduncan** [comment]
@wei9528 can you confirm that this is working for you now?

**Comment by wei9528** [comment]
I am still having problem logging into staging2
![截屏2022-09-30 09 47 23](https://user-images.githubusercontent.com/67583075/193172523-6dfa2cc8-2b30-49d7-b104-c09dcf774b5d.png)

**Comment by jamesduncan** [comment]
@wei9528 have you been able to confirm this yet? Or does the site still not load for you?

**Comment by wei9528** [comment]
@jamesduncan staging2 still does not load for me, and it seems Production is not ready for testing.
